### ISSUE TITLE
Changing Extension order makes config-full and config-sparse go out of sync

### ISSUE THREAD

**Issue by gynt** [UnofficialCrusaderPatch/UCP3-GUI#202]
Use 3 non co-dependent extensions to reproduce

Likely issue: extension order is only saved to config-full, but read from config-sparse.

**Comment by gynt** [comment]
Turns out the order is saved appropriately to the full config, but refreshing the UI does not reproduce that order. It seems to prefer a different order altogether, maybe dictated by `lean-resolution`?

**Comment by gynt** [comment]
@Krarilotus reported he experiences this issue (again?)

**Comment by Krarilotus** [comment]
Example of something that could have to do with this, i am not 100% sure, but its super confusing:
i have this setup:
![image](https://github.com/user-attachments/assets/ce46f792-ac19-4dbb-a752-5edad4d9591c)
Then i click right Legends of the Orient extension, getting this result:
![image](https://github.com/user-attachments/assets/ffa4bbae-712b-4846-9db4-be7b5c4fedf6)
clicking right the Krarilotus-aggressive-AIC next:
![image](https://github.com/user-attachments/assets/0e5c071a-8d9e-47d1-8773-f159b0a212ea)

Problem: The GUI does **not save the order** which i had my plugins before a change occurred, making everything i can setup obsolete and i will have to redo things if i changed the order.
Same is also true for completely unrelated extensions (if you think it was just because aggressive behaviour is part of vanilla retraced), like say the time-provider plugin. Anything put to the right side reshuffles the extensions previously setup in the 'intended' order into a now kinda artificially ordered order i assume, as the new order is always the same for the same previous plugins, regardless of what i changed in their order before.

So i guess the problem isn't fixed, as the changes made in the order are not yet saved to the config, that is loaded on any possible occasion that the config is loaded or updated.

**Comment by gynt** [comment]
This is a different issue, but a nice report, I will refer to it in a new one
