### ISSUE TITLE
[QOL]: Last selected installation path is not saved between GUI restarts

### ISSUE THREAD

**Issue by gynt** [UnofficialCrusaderPatch/UCP3-GUI#244]
https://github.com/UnofficialCrusaderPatch/UCP3-GUI/issues/241#issue-2459099340

**Comment by TheRedDaemon** [comment]
The issue here is related to the fact that the last folder paths are still saved in the global condig file (along the currently not via GUI changeable file log setting for the GUI). The reason is related to Tauris file safety. To allow all saved paths after a restart/reload, the Tauri side needs to allow them, and there is no real solution to allow this from the frontend side (outside the file modals) without basically allowing the code to permit every path/file, at which point we could just disable this safety setting.

At the moment, the folders are saved on a proper shutdown via a hook. I wanted to avoid constant writes to the file. Now, the fact that this one is not triggered by the restart is worth investigating.

**Comment by TheRedDaemon** [comment]
_Analysis_:  
Behaviour is reproducible. The assumption here is that the restart does not trigger the exit event that save the config file.  
No other event seems fitting ([DOCS](https://docs.rs/tauri/latest/tauri/enum.RunEvent.html)), so the solution is likely to control the saving process on the GUI side, either completely or as additional feature. As part of this, the window events should be tested which of them trigger on close and which on restart.

**Comment by TheRedDaemon** [comment]
The issue will now be handled via the lifecycle changes in `feature-improved-game-folder-lifecycle`.
This will remove the GUI relaunch needed for certain changes. The only remaining case would be Updater relaunches, and these can not be handled anyway.

Stay open until the changes are on main.

**Comment by gynt** [comment]
Resolved with 9188589ec06b1cb03a9a36fbb33a0f7244a57280
